// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdwyvzwqgpucenfwprij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkd3l2endxZ3B1Y2VuZndwcmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTQ2NDMsImV4cCI6MjA2Mjc5MDY0M30.uiFXnOxmHhxjljZcI3aTUFVfERKoD6tiMVq4adW2rcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);